# Login
POST http://localhost:3265/api/user/login
Cookie: juicyck={{juicyck}}
Content-Type: application/json;charset=UTF-8

{
  "username": "juicyjusung",
  "password": "juicyjusung"
}
> {%
all_headers = response.headers.headers;
for (i = 0; i < all_headers.length; i++) {
    if ( all_headers[i].name === "Set-Cookie")
    {
        cookieStr=all_headers[i].value.split(";")[0];
        cookieName=cookieStr.split("=")[0];
        cookieValue=cookieStr.split("=")[1];
        client.global.set( cookieName, cookieValue );
    }
}
%}


### Logout
POST http://localhost:3265/api/user/logout
Cookie: juicyck={{juicyck}}
Content-Type: application/json;charset=UTF-8


### Signup
POST http://localhost:3265/api/user/signup
Content-Type: application/json;charset=UTF-8

{
  "username": "juicyjusung4",
  "email": "juicyjusung4@gmail.com",
  "password": "juicyjusung4"
}

### get post
GET http://localhost:3265/api/post/3
Content-Type: application/json;charset=UTF-8

###
POST http://localhost:3265/api/comment/3
Content-Type: application/json;charset=UTF-8
Cookie: juicyck={{juicyck}}


{
  "content": "3번 게시글 juicy2의 댓글"
}

### GET /api/comment/:pid 해당 게시글 댓글들 가져오기
GET http://localhost:3265/api/comment/3
Cookie: juicyck={{juicyck}}
Content-Type: application/json;charset=UTF-8

###

### DELETE /api/comment/:pid 해당 게시글 댓글들 가져오기
DELETE http://localhost:3265/api/comment/3
Cookie: juicyck={{juicyck}}
Content-Type: application/json;charset=UTF-8

{
"commentId": "2"
}

###
PATCH http://localhost:3265/api/comment/3
Cookie: juicyck={{juicyck}}
Content-Type: application/json;charset=UTF-8

{
  "commentId": "3",
  "content": "변경된 댓글입니다"
}

###

